[package]
name = "embedded-bdf-macros"
version = "0.1.0"
authors = ["Ralf Fuest <mail@rfuest.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
bdf-parser = { path = "../bdf-parser" }
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
embedded-graphics = "0.7.0-alpha.2" 
